# Generated by Django 2.2 on 2021-05-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
