# Generated by Django 2.2 on 2021-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
