# Generated by Django 2.2 on 2021-05-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav', '0003_book_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desc',
            new_name='description',
        ),
    ]
