# Generated by Django 2.2 on 2021-05-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav', '0004_auto_20210518_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
